[package]
name = "cjsmessaert/astro-starter-5c1"
version = "0.2.4"
description = "Astro.dev Wasmer starter package"
readme = "README.md"
repository = "https://github.com/cjsmessaert/astro-starter-5c1"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
